name: retune
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#DD1A1C"
  image: assets/icon.png
  android_12: 
    image: assets/icon.png
  android: true
  ios: false
  web: false